# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ploodev
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  region: eu-north-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:eu-north-1:571600828520:table/Messages
            - arn:aws:dynamodb:eu-north-1:571600828520:table/Messages/index/userName-index

build:
  esbuild:
    minify: true

package:
  individually: true

functions:
  getAllMsg:
    handler: functions/getAllMsg/getAllMsg.handler
    events:
      - httpApi:
          path: /messages
          method: GET

  getUserMsg:
    handler: functions/getUserMsg/getUserMsg.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: GET

  postNewMsg:
    handler: functions/postNewMsg/postNewMsg.handler
    events:
      - httpApi:
          path: /messages
          method: POST

  updateMsg:
    handler: functions/updateMsg/updateMsg.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: PUT

  deleteMsg:
    handler: functions/deleteMsg/deleteMsg.handler
    events:
      - httpApi:
          path: /messages/{id}
          method: DELETE

resources:
  Resources:
    Messages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Messages
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
          - AttributeName: 'userName'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'userName-index'
            KeySchema:
              - AttributeName: 'userName'
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
